# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5                       # Number of links shown in pagination
    default_options:
        page_name: page                  # Page query parameter name
        sort_field_name: sort            # Sort field parameter name
        sort_direction_name: direction    # Sort direction parameter name
        distinct: true                    # Ensure distinct results
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'