app_google_oauth:
    path: /oauth/google
    controller: App\Controller\GoogleOAuthController::redirectToGoogle
    methods: [GET]

app_google_callback:
    path: /oauth/google/callback
    controller: App\Controller\GoogleOAuthController::handleGoogleCallback
    methods: [GET]
